apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-pod-label
  template:
    metadata:
      labels:
        app: nginx-pod-label
    spec:
      nodeName: node2
      containers:
      - name: nginx-test
        image: nginx
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 0                      #设置以ROOT用户运行容器
          privileged: true
        ports:
        #- containerPort: 8088 #这里指的是容器内的端口,而不是映射出来到宿主机的端口,必须是80
        - containerPort: 80
        volumeMounts:
          - name: nginx-home
            mountPath: /usr/local/nginx
      volumes:
        - name: nginx-home
          hostPath:
            #path: /data/devops/nginx-test
            path: /root/nginxtest
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-test-svc
  labels:
    #app: nginx-pod-label
    app: nginx-test-svc
spec:
  type: NodePort
  ports:
  - port: 8088
    name: nginx-service80
    protocol: TCP
    #targetPort: 8088
    targetPort: 80
    nodePort: 30832
  selector:
    #app: nginx-test-svc
    #app: nginx1111
    app: nginx-pod-label
