apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx0428
  name: nginx0428-svc-headless
  namespace: default
spec:
  clusterIP: None
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx0428
