apiVersion: v1
kind: Pod
metadata:
  name: sa-demo
  namespace: serviceaccount
  labels:
    app: myapp
spec:
  containers:
  - name: myapp
    image: nginx
    ports:
    - name: httpd
      containerPort: 80
  #serviceAccountName: admin
  #automountServiceAccountToken: false
