apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-servie
  name: nginx-service
  # 命名空间，没有可以删除，默认是default
  namespace: default
spec:
  ports:
  # 对外暴露的端口
  - nodePort: 30013
    port: 9000
    protocol: TCP
    targetPort: 80
  selector:
    # 这里选pod的label 不是deployment的label
    app: nginx-pod
  # NodePort类型可以对外暴露端口
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deploy
  name: nginx-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      labels:
        app: nginx-pod
      namespace: default
    spec:
      containers:
      # 镜像名称
      - image: nginx:1.20.0
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
