apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: myapp-deploy0704
  name: myapp-deploy0704
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-deploy0704
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myapp-deploy0704
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: myapp-deploy0704
        resources: {}
status: {}
