apiVersion: v1
kind: Service
metadata:
  name: myapp-svc-headless
  namespace: default
spec:
  selector:
    app: myapp-test0501
    release: canary
  clusterIP: None
  ports:
  - port: 80
    targetPort: 80 
