apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: pod-serviceaccount-demo
  name: pod-serviceaccount-demo
  namespace: default
spec:
  containers:
  - name: myapp
    image: ikubernetes/myapp:v1
    ports: 
    - name: http
      containerPort: 80
  serviceAccountName: mysa
